/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo de Pedro
 */
public class frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipal
     */
    
    
    public frmprincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.CargarOpcionesmenu();
    }
    
    
    private void CargarOpcionesmenu(){
    
        switch (negocio.Variables.rolId) {
            case 1:
                mnuConfiguracion.setVisible(true);
                mnuCompras.setVisible(true);
                mnuFacturacion.setVisible(true);
                mnuInventario.setVisible(true);
                mnuPlanificacion.setVisible(true);
                mnuProducion.setVisible(true);
                mnuRecursosHumanos.setVisible(true);
                break;
            case 2:
                mnuConfiguracion.setVisible(false);
                mnuCompras.setVisible(true);
                mnuFacturacion.setVisible(true);
                mnuInventario.setVisible(true);
                mnuPlanificacion.setVisible(false);
                mnuProducion.setVisible(true);
                mnuRecursosHumanos.setVisible(true);
                break;
            case 3:
                mnuConfiguracion.setVisible(false);
                mnuCompras.setVisible(false);
                mnuFacturacion.setVisible(false);
                mnuInventario.setVisible(true);
                mnuPlanificacion.setVisible(true);
                mnuProducion.setVisible(true);
                mnuRecursosHumanos.setVisible(false);
                break;
            default:
                mnuConfiguracion.setVisible(true);
                jMenuItem8.setVisible(false);
                jMenuItem9.setVisible(false);
                jMenuItem12.setVisible(true);
                mnuCompras.setVisible(false);
                mnuFacturacion.setVisible(false);
                mnuInventario.setVisible(false);
                mnuPlanificacion.setVisible(false);
                mnuProducion.setVisible(false);
                mnuRecursosHumanos.setVisible(false);
                
                break;
        }
    
    
    }
    
    
    
    
     public void cerrar(){
    Object [] opciones ={"Aceptar","Cancelar"};
    int eleccion = JOptionPane.showOptionDialog(rootPane,"Desea Cerrar El Sistema?","Sistema",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
    if (eleccion == JOptionPane.YES_OPTION)
    {
    System.exit(0);
    }else{
    }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuConfiguracion = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuPlanificacion = new javax.swing.JMenu();
        mnuInventario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuProducion = new javax.swing.JMenu();
        mnuFacturacion = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mnuRecursosHumanos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMP Sistema de Control de producion");

        mnuConfiguracion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\engranaje (1).png")); // NOI18N
        mnuConfiguracion.setText("Configuracion");
        mnuConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuConfiguracion.setMargin(new java.awt.Insets(2, 2, 2, 10));
        mnuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConfiguracionActionPerformed(evt);
            }
        });

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\grupo.png")); // NOI18N
        jMenuItem8.setText("Roles");
        jMenuItem8.setMargin(new java.awt.Insets(2, 2, 5, 2));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\usuario (2).png")); // NOI18N
        jMenuItem9.setText("Usuario");
        jMenuItem9.setMargin(new java.awt.Insets(2, 2, 5, 2));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(jMenuItem9);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\salida.png")); // NOI18N
        jMenuItem12.setText("Salir");
        jMenuItem12.setMargin(new java.awt.Insets(2, 2, 5, 2));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(jMenuItem12);

        menuBar.add(mnuConfiguracion);

        mnuCompras.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\portapapeles.png")); // NOI18N
        mnuCompras.setText("Compras");
        mnuCompras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuCompras.setMargin(new java.awt.Insets(2, 2, 2, 10));
        mnuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprasActionPerformed(evt);
            }
        });

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\inventario2.png")); // NOI18N
        jMenuItem3.setText("Provedores");
        jMenuItem3.setMargin(new java.awt.Insets(2, 2, 5, 2));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuCompras.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\proceso.png")); // NOI18N
        jMenuItem4.setText("Orden de Compra");
        jMenuItem4.setMargin(new java.awt.Insets(2, 2, 5, 2));
        mnuCompras.add(jMenuItem4);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\grabar.png")); // NOI18N
        jMenuItem10.setText("Consulta Compras");
        jMenuItem10.setMargin(new java.awt.Insets(2, 2, 5, 2));
        mnuCompras.add(jMenuItem10);

        menuBar.add(mnuCompras);

        mnuPlanificacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\grafico.png")); // NOI18N
        mnuPlanificacion.setText("Planificacion");
        mnuPlanificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuPlanificacion.setMargin(new java.awt.Insets(2, 2, 2, 10));
        menuBar.add(mnuPlanificacion);

        mnuInventario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\inventario.png")); // NOI18N
        mnuInventario.setText("Inventario");
        mnuInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuInventario.setMargin(new java.awt.Insets(2, 2, 2, 10));

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\mas (1).png")); // NOI18N
        jMenuItem1.setText("Categoria");
        jMenuItem1.setMargin(new java.awt.Insets(2, 2, 4, 2));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuInventario.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\producto8.png")); // NOI18N
        jMenuItem2.setText("Productos");
        jMenuItem2.setMargin(new java.awt.Insets(2, 2, 4, 2));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuInventario.add(jMenuItem2);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\mas.png")); // NOI18N
        jMenuItem5.setText("Recepcion");
        jMenuItem5.setMargin(new java.awt.Insets(2, 2, 4, 2));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuInventario.add(jMenuItem5);

        menuBar.add(mnuInventario);

        mnuProducion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\linea-de-ensamble.png")); // NOI18N
        mnuProducion.setText("Producion");
        mnuProducion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuProducion.setMargin(new java.awt.Insets(2, 2, 2, 10));
        menuBar.add(mnuProducion);

        mnuFacturacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\facturacion.png")); // NOI18N
        mnuFacturacion.setText("Facturacion");
        mnuFacturacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuFacturacion.setMargin(new java.awt.Insets(2, 2, 2, 10));

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\usuario (3).png")); // NOI18N
        jMenuItem6.setText("Cliente");
        jMenuItem6.setMargin(new java.awt.Insets(2, 2, 5, 2));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuFacturacion.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\menos0.png")); // NOI18N
        jMenuItem7.setText("Ventas");
        jMenuItem7.setMargin(new java.awt.Insets(2, 2, 5, 2));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuFacturacion.add(jMenuItem7);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\contabilidad.png")); // NOI18N
        jMenuItem11.setText("Consulta ventas");
        jMenuItem11.setMargin(new java.awt.Insets(2, 2, 5, 2));
        mnuFacturacion.add(jMenuItem11);

        menuBar.add(mnuFacturacion);

        mnuRecursosHumanos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo de Pedro\\Desktop\\Proyecto Producion en masa\\Iconos\\humano.png")); // NOI18N
        mnuRecursosHumanos.setText("Recursos Humanos");
        mnuRecursosHumanos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuRecursosHumanos.setMargin(new java.awt.Insets(2, 2, 2, 10));
        menuBar.add(mnuRecursosHumanos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    FrmCategoria frm = new FrmCategoria();
    escritorio.add(frm);
    frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
    frm.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    FrmArticulo frm = new FrmArticulo();
    escritorio.add(frm);
    frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
    frm.setVisible(true);   
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConfiguracionActionPerformed
    
        
        
    }//GEN-LAST:event_mnuConfiguracionActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
      FrmRol frm = new FrmRol();
      escritorio.add(frm);
      frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
      frm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       this.cerrar();
        
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       FrmUsuario frm = new FrmUsuario();
       escritorio.add(frm);
       frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
       frm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprasActionPerformed
     
        
        
    }//GEN-LAST:event_mnuComprasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       FrmProvedor frm = new FrmProvedor();
       escritorio.add(frm);
       frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
       frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       FrmCliente frm = new FrmCliente();
       escritorio.add(frm);
       frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
       frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       FrmEntradas frm = new FrmEntradas(this);
       escritorio.add(frm);
       frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
       frm.setVisible(true); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
     
       FrmSalida frm = new FrmSalida(this);
       escritorio.add(frm);
       frm.setLocation((escritorio.getWidth()/2)-frm.getWidth()/2,(escritorio.getHeight()/2) -frm.getHeight()/2);
       frm.setVisible(true); 
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuCompras;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenu mnuFacturacion;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenu mnuPlanificacion;
    private javax.swing.JMenu mnuProducion;
    private javax.swing.JMenu mnuRecursosHumanos;
    // End of variables declaration//GEN-END:variables

}
